# Generated by Django 4.2.1 on 2023-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesearchword',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipesearchword',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
