# Generated by Django 4.2.1 on 2023-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_update_recipe_search_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
